Concert Music Site/config/routes.rb
Rails.application.routes.draw do

  resources :concerts do
    resources :comments
  end
  get '/' => "concerts#home"

  get '/home' => "concerts#home"
  get '/upcoming' => "concerts#upcoming"
  get '/getcomments/:id' => 'comments#send_comments'
  post '/addcomments/:id' => 'comments#add_comments'

  get '/songsearch' => 'songsearch#main'
  get '/sign_up' => "users#new"
  post '/users' => "users#create"
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"

end

Concert Music Site/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :concert
end

Concert Music Site/app/models/concert.rb
class Concert < ActiveRecord::Base
	
	has_many :comments
	validates 	:artist, presence: true
	validates	:date, presence: true
	validates	:venue, presence: true
	validates	:city, presence: true
	validates	:ticket_price,  presence: true, numericality: true
	
end

Concert Music Site/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :password, presence: true
  	validates :username, presence: true
  	validates :email, presence: true, uniqueness: true
end

Concert Music Site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   helper_method :current_user

  def current_user
  	if @current_user.nil?
  		@current_user = User.find_by(id: session[:user_id])
  	end
  	@current_user
  end  

end

Concert Music Site/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		concert = Concert.find(params[:concert_id])
		comment = concert.comments.new(comment_params)
		if comment.save
			flash[:notice] = "Success!"
		end
			redirect_to concert_path(params[:concert_id])

	end
	def send_comments

		artist = Concert.find(params[:id].chars.first)

		artist.comments.order(created_at: :ASC)
		
		render(:json => artist.comments)
	end

	def add_comments
		p params
		concert = Concert.find(params[:concert_id].chars.first)

		comment = concert.comments.new(:title => params[:title],:description => params[:description] )
		p concert
		p comment
		if comment.save 
			puts " SAVED"
		end
		render nothing: true
		
	end

	private
	def comment_params
		return params.require(:comment).permit(:title, :description)
	end
end

Concert Music Site/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

	def show
		@comment = Comment.new
		@concert = Concert.find(params[:id])
		artists =  RSpotify::Artist.search(@concert.artist)
		@artist = artists[0]
		
		render 'show'
	end

	def upcoming
		@concerts_today = Concert.where(:date => Date.today)
		@concerts_upcoming = Concert.where('date >= ?', DateTime.now)
		.order("extract(day from date) ASC")
		
			render 'upcoming'
	end

	def new
		@concert = Concert.new
		render 'new'
	end

	def index
		@concerts = Concert.all
		render 'index'
	end

	def create
		
		@concert = Concert.new(concert_params)

		if @concert.save 
			flash[:notice] = "Added new concert!"
			redirect_to action: 'index', controller: 'concerts'
		else 
			flash[:alert] = "Creation Failed."
			render 'new'
		end
	end

	def home
		@concerts_today = Concert.where(:date => Date.today)
		@concerts_month = Concert.where('extract(month from date) = ?', Time.now.month).where('extract(year from date) = ?', Time.now.year).order("extract(day from date) ASC")
			render 'home'
	end
	

	def update

	end

	private
	def concert_params
		return params.require(:concert).permit(:venue, :description, :date, :ticket_price, :city, :artist)
	end
end

Concert Music Site/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
		def new

		render 'new'

	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id

			redirect_to '/'
		else
			redirect_to '/login'

		end
		
	end

	def destroy
			session.clear
			redirect_to '/'

	end
end

Concert Music Site/app/controllers/songsearch_controller.rb
class SongsearchController < ApplicationController
	def main
		render('main')
	end
end

Concert Music Site/app/controllers/users_controller.rb
class UsersController < ApplicationController


  # renders the signup form
  def new
  end



  # receives form and creates a user from that data
  def create
    user = User.new(user_params)
    if user.save
      redirect_to '/'
    else
      redirect_to '/sign_up'
    end
  end   

  private

  def user_params
     params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

Concert Music Site/app/helpers/application_helper.rb
module ApplicationHelper
	def pretty_date(date)
		return date.strftime("%B %-d, %Y")
	end
end

Concert Music Site/app/helpers/comments_helper.rb
module CommentsHelper
end

Concert Music Site/app/helpers/concerts_helper.rb
module ConcertsHelper
end

Concert Music Site/app/helpers/sessions_helper.rb
module SessionsHelper
end

Concert Music Site/app/helpers/songsearch_helper.rb
module SongsearchHelper
end

Concert Music Site/app/helpers/users_helper.rb
module UsersHelper
end

Concert Music Site/app/views/partials/_footer.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom" >
  <div class="container-fluid" >
     <div class="navbar-header">
		<h5 style="color: white; line-height: 2.3;">Copyright Cesar Ferrat @Ironhack <%= Time.now.year %></h5>
    
    </div>
    
    	<ul class="nav navbar-nav pull-right">
	  		<% if current_user.present? %>		
		        <li><a href="<%= new_concert_path %>">Add new Concert</a></li>
		    <% end%>

	   	</ul>
  </div>
</nav>

Concert Music Site/app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= home_path %>">Cesar's Music Network</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
      <% if current_user.present? %>    
            
            <li><%=link_to "Logout", '/logout', :method => :delete %></li>  
        <% else %>
          <li> <%=link_to "Login", '/login'%></li>  
          <li> <%=link_to "Sign Up", '/sign_up'%></li>  
        <% end%>
      </ul>
      <div class="nav navbar-brand pull-right">
  <% if current_user.present? %>
  Signed in as 
      <%= current_user.username %>
    <% end %>
    

    </div>
      <ul class="nav navbar-nav pull-left">
        <li><a href="<%= home_path %>">Home</a></li>
        <li><a href="<%=upcoming_path%>">Upcoming Concerts</a></li>
        <li><a href="<%= concerts_path %>">All concerts</a></li>
        <li><a href="<%= songsearch_path %>">Song Search</a></li>
      </ul>
    
      
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

Concert Music Site/app/views/partials/_reactshow.html.erb
<script>

<div style="height:300px; width: 300px; margin-left: 100px;">
<%= render './partials/reactshow' :locals => {:greeting => 'Hello world', :x => 36}%>
</div>

</script>




<%= react_component ('Main', searchResult: <%= search %>) %>

Concert Music Site/app/views/songsearch/main.html.erb
<div class="col-lg-1">

</div>
	<div class="col-lg-7">
					
		<div class="panel panel-default">

			<div class="panel-body" style="padding: 0px;">
				<div class="container-fluid">
					<h1 class="jumbotron" style="border-radius:20px; padding: 20px">Search Track<br><small>Previews</small></h1>
					
						<div class="col-md-6">
							
								<div class="input-group  has-validation">
									<input class="form-control has-success" name = "search">
									<span class="input-group-btn">
									<button type="submit" class="btn btn-default" onClick="onSearchSubmit()" >Search</button>
									</span>
								</div>

						</div>
						<div class="col-md-6">
							<div class="widget">
								<div class="cover">
								<img src="https://i.scdn.co/image/04da6dfc1f5f45fdeba938a0cc71cf372524fd43" class="js-player-image">
								</div>
								<div class="heading">
								<!-- Try adding/removing these classes: -->
								<!-- disabled -->
								<!-- playing -->
								<div class="btn-play" onclick="onPlayButtonClick()"></div>

								<div class="metadata">
								  <p class="title">Hunger of The Pine</p>
								  <a class="over-hover"href="#" onclick="$('#artistModal').modal()"><p class="author">alt-J</p></a>

								  <div class="seekbar">
								    <progress value="0" max="30"></progress>
								  </div>
								</div>
								</div>
								

								<audio src="https://p.scdn.co/mp3-preview/8e9c5ffdc38e91659bfe8b6bd44650dfc25a3d31" class="js-player" ontimeupdate='updateTrackTime()'></audio>
							</div>
							
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-4">
		
	</div>

	<div class="modal fade" id="artistModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="artistModalLabel">Please search for a new artist</h4>
	      </div>
	      <div class="modal-body">
			<div class="container-fluid">
				<div class="col-xs-6">
					<img id='image' src='' width="250px">
				</div>
				<div class="col-xs-6">
					<div class="container-fluid">
						<div class="row" id="genre">	
						</div>
						<div class="row">
							<h5>Followers on Spotify:</h5>
							<span id="followers">Search First</span>
						</div>
						<div class="row">
							<h5>Popularity:</h5>
							<span id="pop">Search First</span>
						</div>	
					</div>
				</div>
			</div>
			

	        	<!-- 
				 
				$('#pop').val(artist.popularity); 
				
 -->
	      </div>
	    
	    </div>
	  </div>
	</div>

Concert Music Site/app/views/users/new.html.erb
<div class="form col-lg-3 white-text">
<h1 class="jumbotron black-text" style="border-radius:20px;">Sign up!</h1>
<%= form_for :user, url: '/users' do |f| %>
	<div class = "form-group has-validation">	
  Name <%= f.text_field :username, class: "form-control white-text" %>
  </div>
	<div class = "form-group has-validation">  
  Email <%= f.text_field :email, class: "form-control white-text" %>
  </div>
	<div class = "form-group has-validation">
  Password  <%= f.password_field :password, class: "form-control white-text" %>
  </div>
	<div class = "form-group has-validation">
  Confirmation 
  <%= f.password_field :password_confirmation, class: "form-control white-text " %>
  </div>
  <%= f.submit "Submit", class: 'btn btn-primary' %>

<% end %>
</div>