BBQ-heroku/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'barbecues#index'

  resources :barbecues, only: [ :index, :show, :new, :create ]

  get '/api/barbecues/:id' => 'barbecues#showBBQ'
  #join a bbq
  post '/api/barbecues/:id/join' => 'barbecues#joinBBQ'
  #add item to bbq
  post '/api/barbecues/:id/addItem' => 'barbecues#addItem'
  #show user
  get '/users/showUser/:id' => 'users#showUser'
  #remove bbq
  delete '/users/removeBBQ/:id' => 'barbecues#removeBBQ'
  #get comments for bbq
  get '/api/barbecues/:id/Comments' => 'barbecues#getComments'
  post '/api/barbecues/:id/Comments' => 'barbecues#addComments'
end

BBQ-heroku/app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :user
	belongs_to :barbecue
	
end

BBQ-heroku/app/models/barbecue.rb
class Barbecue < ActiveRecord::Base
  validates :title, presence: true
  validates :venue, presence: true
  validates :date, presence: true
  has_many :users, :through => :attendances
  has_many :attendances
  has_many :items
  has_many :comments
end

BBQ-heroku/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

BBQ-heroku/app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :barbecue
	belongs_to :user
end

BBQ-heroku/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :barbecues, :through => :attendances
  has_many :attendances
  has_many :items
  has_many :comments

  include Gravtastic
  has_gravatar
end

BBQ-heroku/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
before_action :configure_devise_permitted_parameters, if: :devise_controller?


  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

BBQ-heroku/app/controllers/barbecues_controller.rb
class BarbecuesController < ApplicationController
  
  before_action(:authenticate_user!)
  def index

    @barbecues = Barbecue.order(:date)
  end

  def show
    @users = User.all
    @bbq = Barbecue.find_by(:id => params[:id])
    @items = @bbq.items
  end

  def addItem
    bbq = Barbecue.find_by(:id => params[:id])
    user = current_user.id
    newItem = Item.create(:name => params[:itemName])
    current_user.items.push(newItem)
    bbq.items.push(newItem)
    render :status => 200, :json => {
      :response => "Successful"
    }
    
  end

  def removeBBQ
    bbq = Barbecue.find_by(:id => params[:id])
    current_user.barbecues.delete(bbq)
    render :status => 200, :json => {
          :response => "Confirmed"
        }
  end

  def showBBQ

    bbq = Barbecue.find_by(:id => params[:id])
    bbqPackage = {
      :title => bbq.title,
      :date => bbq.date,
      :venue => bbq.venue
    }
    render :status => 200, :json => bbqPackage

  end

  def joinBBQ

    bbq = Barbecue.find_by(:id => params[:id])
    
    if current_user.present?
      
      if current_user.barbecues.push(bbq)
      render :status => 200, :json => {:response => "Attempt to add bbq completed."}
      else
        render :status => 400, :json => {:response => "Attempt to add bbq failed. Please verify that you are logged in."}
      end

    else
      render :status => 400, :json => {:response => "Attempt to add bbq failed. Please verify that you are logged in."}
    end
  end

  def getComments
    bbq = Barbecue.find_by(:id => params[:id])
    commentsArray = []

    bbq.comments.each do |comment|
      commentUsername = User.find_by(:id => comment.user_id).name
      p commentUsername
      newComment = {
          :user => commentUsername,
          :content => comment.content,
          :date => format_date(comment.created_at)
      }
      commentsArray.push(newComment)
    end

    if bbq.present?
      render :status => 200, :json => commentsArray
    else
      render :status => 404, :json => {:response => "Request failed"}
    end

  end
  def addComments
    bbq = Barbecue.find_by(:id => params[:id])
    
    
    newComment = Comment.create(:content => params[:text], :user_id => current_user.id)
    bbq.comments.push(newComment)

   
    render :status => 200, :json => {:response => "Success"}
  end

  def new
    @bbq = Barbecue.new
  end

  def create
    bbq_params = params.require(:barbecue).permit(:title, :venue, :date)
    @bbq = Barbecue.new(bbq_params)

    unless @bbq.save
      render(:new)
    else
      redirect_to(barbecues_path)
    end
  end
  private
  def format_date(date)
    return date.strftime('%B, %e %Y at %l:%M %P')
  end


end

BBQ-heroku/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action(:authenticate_user!)
	def showUser
		@user = User.find_by(:id => params[:id])
		if @user.present?
			render "show"
		else
			redirect_to(barbecues_path)
		end
	end
	
end

BBQ-heroku/app/helpers/application_helper.rb
module ApplicationHelper
end

BBQ-heroku/app/helpers/barbecues_helper.rb
module BarbecuesHelper
  def format_date(date)
    return date.strftime('%B, %e %Y at %l:%M %P')
  end
end

BBQ-heroku/app/helpers/users_helper.rb
module UsersHelper
	 def format_date(date)
    return date.strftime('%B, %e %Y at %l:%M %P')
  end
end

BBQ-heroku/app/views/barbecues/index.html.erb
<h1>BBQs</h1>

<a href="<%= new_barbecue_path %>" class="btn btn-primary">
  Add a new BBQ
</a>

<ul class="list-unstyled">
  <% @barbecues.each do |bbq| %>
    <li data-bbq="<%= bbq.id %>">
      <h2>
        <a href="<%= barbecue_path(bbq.id) %>">
          <%= bbq.title %>
        </a>
      </h2>

      <dl>
        <dt>Date:</dt>
        <dd><%= format_date(bbq.date) %></dd>
        <dt>Venue:</dt>
        <dd><%= bbq.venue %></dd>
      </dl>

      <% unless current_user.barbecues.include?(bbq) %>
      <button class="btn btn-success" data-hook="join-bbq">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Join <%= bbq.title %>
      </button>
      <% end %>
    </li>
  <% end %>
</ul>
<% if current_user.present? %>
    <%= react_component('Box', props= {email: current_user.email}, html_options={:class => "react_box"}) %>
  <% end %>

BBQ-heroku/app/views/barbecues/new.html.erb
<h1>Add a new BBQ</h1>

<% if @bbq.errors.any? %>
  <ul class="list-unstyled">
    <% @bbq.errors.full_messages.each do |msg| %>
      <li class="alert alert-danger" role="alert"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @bbq do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :venue %>
    <%= form.text_field :venue, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <button type="submit" class="btn btn-success">
    Add BBQ
  </button>
<% end %>
<% if current_user.present? %>
    <%= react_component('Box', props= {email: current_user.email}, html_options={:class => "react_box"}) %>
  <% end %>

BBQ-heroku/app/views/barbecues/show.html.erb
<h1>BBQ</h1>
<div class="container-fluid">
	<div class="col-lg-5 col-md-6 col-sm-6 col-xs-12">
		<div data-hook="bbq-info" data-bbq="<%= params[:id] %>"></div>
		Items People are bringing:
		<ul class="" data-hook="items-list">
			<% @items.each do |item| %>
				<li><%= item.name %> - <a href="/users/showUser/<%= item.user_id %>"><%= User.find_by(:id => item.user_id).name %></a></li>
			<% end %>
		</ul>
		
		<div class="form-group">
			<label>Add Item</label>
			<input class="form-control" type="text" data-hook='item-input'>
		</div>
		
		<button class="btn btn-primary" id="<%= @bbq.id%>" type='submit' data-hook="submit-item">Add</button>
		<br>

		<a href="<%= barbecues_path %>">Back to list of BBQs</a>
	</div>

	<div class="col-lg-7 col-md-6 col-sm-12 col-xs-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Whos coming?:</h4> 
			</div>
			<div class="panel-body">
				<!-- <ul class="list-unstyled"> -->
					<% @bbq.attendances.each do |user| %>

						<div class="col-sm-6"><a href="/users/showUser/<%= user.id %>"><%= User.find_by(:id => user.id).name  %></a></div>
					<% end %>
				<!-- </ul> -->
			</div>
		</div>
		
	</div>
	<div class="col-lg-7 col-md-6 col-sm-12 col-xs-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Comments</h4>
			</div>
			<div class="panel-body">
				<%= react_component('CommentBox', props = {:url => "/api/barbecues/#{@bbq.id}/Comments", :pollInterval => 1000, :user_id => current_user.id}) %>
			</div>
			
		</div>
	</div>
</div>
<% if current_user.present? %>
	 	<%= react_component('Box', props= {email: current_user.email}, html_options={:class => "react_box "}) %>
<% end %>